# -*- coding: utf-8 -*-
"""02.19_linearRegression_boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPCntx3eK_xVRqRQw52iUfpOiGxDpPf1
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tensorflow.keras import Sequential,Input
from tensorflow.keras.layers import Dense
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data(
    path='boston_housing.npz', test_split=0.1, seed=113)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_train[0])
print(y_train[0])
#0."마을별 1인당 범죄율(CRIM)"]
#1. 주거용 토지비율.
#2. 도시당 소매점을 제외한 비즈니스 비율(회사비율)
#3. 강을 경계하는 경우 1, 그렇지 않은 경우 0
#4. 일산화질소 농도(1천만 분의 1) - 공기질
#5. 평균 방 수
#6. 주택의 나이
#7. 보스턴 고용 센터 5곳까지의 거리-일자리지원여부
#8. 고속도로 접근성
#9. 재산세율
#10. 학생-교사 비율
#11. 마을별 흑인 비율
#12. 낮은 인구밀도
# 정답단위 1,0000달러

#데이터 연관성확인 13개의 데이터
plt.figure(figsize=(6,10))
plt.subplot(7,2,1)
plt.title("0")
plt.scatter(x_train[:,0],y_train,s=10)
plt.subplot(7,2,2)
plt.title("1")
plt.scatter(x_train[:,1],y_train,s=10)
plt.subplot(7,2,3)
plt.title("2")
plt.scatter(x_train[:,2],y_train,s=10)
plt.subplot(7,2,4)
plt.title("3")
plt.scatter(x_train[:,3],y_train,s=10)
plt.subplot(7,2,5)
plt.title("4")
plt.scatter(x_train[:,4],y_train,s=10)
plt.subplot(7,2,6)
plt.title("5")
plt.scatter(x_train[:,5],y_train,s=10)
plt.subplot(7,2,7)
plt.title("6")
plt.scatter(x_train[:,6],y_train,s=10)
plt.subplot(7,2,8)
plt.title("7")
plt.scatter(x_train[:,7],y_train,s=10)
plt.subplot(7,2,9)
plt.title("8")
plt.scatter(x_train[:,8],y_train,s=10)
plt.subplot(7,2,10)
plt.title("9")
plt.scatter(x_train[:,9],y_train,s=10)
plt.subplot(7,2,11)
plt.title("10")
plt.scatter(x_train[:,10],y_train,s=10)
plt.subplot(7,2,12)
plt.title("11")
plt.scatter(x_train[:,11],y_train,s=10)
plt.subplot(7,2,13)
plt.title("12")
plt.scatter(x_train[:,11],y_train,s=10)
plt.show()
# 인덱스 5번과 7번 데이터 결정

#데이터 추출
x_data = x_train[:,[5,7]]
y_data = y_train
print(x_data.shape)
print(y_data.shape)
plt.subplot(1,2,1)
plt.scatter(x_data[:,0],y_data)
plt.subplot(1,2,2)
plt.scatter(x_data[:,1],y_data)
plt.show()

print(x_data[0])

#문제데이터 표준화
mean0=np.mean(x_data[:,0])
std0=np.std(x_data[:,0])
x_data[:,0]=(x_data[:,0]-mean0)/std0
mean1=np.mean(x_data[:,1])
std1=np.std(x_data[:,1])
x_data[:,1]=(x_data[:,1]-mean1)/std1
print(x_data[0])
print(x_data[1])

model = Sequential()
model.add(Input((2,)))
model.add(Dense(1))
model.compile(loss="MSE",optimizer="SGD")

fhist = model.fit(x_data,y_data,epochs=10)

plt.plot(fhist.history["loss"])
plt.show()

x_ts = x_test[:,[5,7]]
print(x_test[1])
#테스트 데이터 정규화
x_ts[:,0]=(x_ts[:,0]-mean0)/std0
x_ts[:,1]=(x_ts[:,1]-mean1)/std1
print(x_ts[1])

y_pred = model.predict(x_ts)

y_gap=y_test-y_pred
y_rat = y_gap/y_test*100 #오차확률
err_mean = np.mean(y_rat)
print("오차확률의 평균은 ± %.2f%%"%(np.abs(err_mean)))

